%% GENERATE_TABLE6 Extracts case study results for Table 5.
%
%   GENERATE_TABLE6() reads the evaluation_dataset_v2.csv and extracts
%   specific segments representing Tier 1, Tier 2, and Tier 3 validation
%   cases. It computes the logarithmic penalty P (P = ln(1+ψ) = Penalty/100)
%   and exports the results as a CSV file for Table 5.
%
%   METHODOLOGY
%   -----------
%   1. The function loads the unified evaluation catalog generated by the
%      master pipeline.
%   2. A predefined list of target substrings (covering TIC 261136679 (S9),
%      KIC 12557548, TOI-201, KIC 11253226, KIC 5812701, KIC 12644769,
%      and V723 Mon) is used to filter the rows.
%   3. For each target, the first matching segment is selected to avoid
%      duplicate entries.
%   4. The Penalty P is calculated as P = Penalty_pct / 100, matching the
%      theoretical definition P = ln(1 + ψ).
%   5. The results are displayed in the Command Window and exported to
%      Table5_CaseStudies.csv.
%
%   INPUTS
%   ------
%   target_list : (Optional) Cell array of strings to search for in
%                 the 'Filename' column. Defaults to the manuscript's
%                 Table 6 targets.
%   outfile     : (Optional) Name of the output CSV file. Default:
%                 'Table5_CaseStudies.csv'.
%
%   OUTPUTS
%   -------
%   CSV File : Table6_CaseStudies.csv with columns:
%              Filename, T_SNR, R_SNR, L_SNRAS, P, Suppression_pct, Tier.
%   Command Window Output : Formatted summary of the extracted segments.
%
%   DEPENDENCIES
%   ------------
%   evaluation_dataset_v2.csv : Must be in the current directory.
%
%   SEE ALSO
%   --------
%   main_pipeline, generate_table6, readtable
function generate_table5(target_list, outfile)
    % Set default arguments
    if nargin < 1
        target_list = {'sector_9', '12557548', 'toi_201', ...
                       '11253226', '5812701', '12644769', 'v723_mon'};
    end
    if nargin < 2
        outfile = 'Table5_CaseStudies.csv';
    end

    % --- 1. Load the evaluation dataset ---
    csv_file = 'evaluation_dataset_v2.csv';
    if ~isfile(csv_file)
        error('File %s not found. Please ensure it exists in the current directory.', csv_file);
    end
    data = readtable(csv_file);
    
    % CRITICAL FIX: Convert 'Filename' and 'Tier' columns to strings to avoid cell-array errors later
    data.Filename = string(data.Filename);
    data.Tier = string(data.Tier);

    % --- 2. Initialize output table ---
    table5_rows = table();

    % --- 3. Search for each target ---
    fprintf('\n=== Extracting Table 5 Case Studies ===\n');
    for k = 1:length(target_list)
        kw = target_list{k};
        mask = contains(lower(data.Filename), lower(kw));
        sub = data(mask, :);
        if height(sub) > 0
            row = sub(1, :); % Take the first matching row
            
            % Calculate P (Logarithmic Penalty)
            % P = ln(1 + psi) = Penalty_pct / 100
            row.P = row.Penalty_pct / 100;
            
            % Append to results
            table5_rows = [table5_rows; row];
            
            % FIXED PRINTF: Convert to char/string to avoid 'cell' input error
            fprintf('  [%s] -> Matched: %s (Tier %s)\n', ...
                char(kw), char(row.Filename), char(row.Tier));
        else
            fprintf('  [%s] -> No match found\n', char(kw));
        end
    end

    % --- 4. Display and save results ---
    if height(table5_rows) == 0
        warning('No rows matched the target list. Output file will be empty.');
    else
        % Define columns required for Table 5
        disp_columns = {'Filename','T_SNR','R_SNR','L_SNRAS','P','Suppression_pct','Tier'};
        
        % Display in Command Window
        disp(table5_rows(:, disp_columns));
        
        % Write to CSV
        writetable(table6_rows(:, disp_columns), outfile);
        fprintf('\n Table 5 saved to: %s\n', outfile);
    end
end
