%% GENERATE_TABLE5 Computes and prints the DeLong exact test results.
%
%   GENERATE_TABLE5() reads the evaluation_dataset_v2.csv, applies the
%   standard quality filtering (N_in >= 30, valid labels and SNR),
%   computes the DeLong exact test comparing the isolated logarithmic
%   penalty (-P) against each raw SNR metric, and prints the results
%   directly to the MATLAB Command Window.
%
%   METHODOLOGY
%   -----------
%   The function uses the same "valid" mask as the master pipeline:
%       valid = ~isnan(Label) & ~isnan(T_SNR) & ~isnan(L_SNRAS) & N_in >= 30.
%   This yields N=98 valid segments for the evaluation.
%
%   For each comparison:
%       1. AUC_penalty is computed for -Penalty_pct.
%       2. AUC_raw is computed for each raw metric.
%       3. Delta AUC = AUC_penalty - AUC_raw is calculated.
%       4. The DeLong z-statistic and two-sided p-value are obtained
%          via the analytic covariance-based U-statistic method
%          implemented in the external deLongExact.m function.
%
%   DEPENDENCIES
%   ------------
%   deLongExact.m : Must be present in the same directory.
%   evaluation_dataset_v2.csv : Generated by the master pipeline.
%
%   OUTPUTS
%   -------
%   Command Window Output : Formatted text table of the DeLong test results.
%
%   SEE ALSO
%   --------
%   deLongExact, analyze_performance, perfcurve
clear; clc; close all;

%% --- 1. LOAD AND FILTER DATA ---
csv_file = 'evaluation_dataset_v2.csv';
if ~isfile(csv_file)
    error('File %s not found. Ensure it exists.', csv_file);
end
results = readtable(csv_file);

% Apply strict quality filtering (matching Table 3 criteria)
valid_mask = ~isnan(results.Label) & ~isnan(results.T_SNR) & ...
             ~isnan(results.L_SNRAS) & (results.N_in >= 30);
results_valid = results(valid_mask, :);
y_true_v = results_valid.Label;
n_valid = sum(valid_mask);

fprintf('Total segments: %d | Valid for DeLong test (N): %d\n', height(results), n_valid);

% Extract the isolated penalty scores (negated for ROC: higher = better)
scores_penalty = -results_valid.Penalty_pct;
[~,~,~,auc_penalty] = perfcurve(y_true_v, scores_penalty, 1);
fprintf('AUC (Isolated Penalty -P) = %.3f\n\n', auc_penalty);

%% --- 2. SETUP RAW METRICS ---
metric_names = {'T-SNR', 'R-SNR', 'P-SNR', 'B-SNR', 'Log-SNRAS'};
metric_cols  = {'T_SNR', 'R_SNR', 'P_SNR', 'B_SNR', 'L_SNRAS'};
n_metrics = length(metric_names);

% Store results for printing
comparison_labels = cell(n_metrics, 1);
delta_auc_vals    = zeros(n_metrics, 1);
z_vals            = zeros(n_metrics, 1);
p_vals            = zeros(n_metrics, 1);

%% --- 3. COMPUTE DELONG COMPARISONS ---
for m = 1:n_metrics
    % Extract raw scores
    raw_scores = results_valid.(metric_cols{m});
    raw_scores(isnan(raw_scores)) = 0; % Replace NaNs with 0 (as in master pipeline)
    
    % Compute raw AUC
    [~,~,~,auc_raw] = perfcurve(y_true_v, raw_scores, 1);
    
    % Compute Delta AUC
    delta_auc = auc_penalty - auc_raw;
    
    % Run DeLong Exact Test (called from the external function!)
    [p_val, z_val] = deLongExact(y_true_v, scores_penalty, raw_scores);
    
    % Store values
    comparison_labels{m} = sprintf('Penalty vs. %s', metric_names{m});
    delta_auc_vals(m)    = delta_auc;
    z_vals(m)            = z_val;
    p_vals(m)            = p_val;
end

%% --- 4. PRINT RESULTS TO COMMAND WINDOW ---
fprintf('\n==============================================================\n');
fprintf('        TABLE 5: DELONG EXACT TEST RESULTS (N = %d)\n', n_valid);
fprintf('==============================================================\n');
fprintf('%-20s | %-8s | %-6s | %-10s\n', 'Comparison', 'ΔAUC', 'z', 'p');
fprintf('--------------------------------------------------------------\n');

for m = 1:n_metrics
    % Format p-value for printing: if < 1e-4, use < 10^-4
    if p_vals(m) < 1e-4
        p_str = '< 10^-4';
    else
        p_str = sprintf('%.4f', p_vals(m));
    end
    
    fprintf('%-20s | %-8.3f | %-6.2f | %-10s\n', ...
        comparison_labels{m}, delta_auc_vals(m), z_vals(m), p_str);
end
fprintf('==============================================================\n');
