%% GENERATE_TABLE7 Extracts targeted segments for batch vetting examples.
%
%   GENERATE_TABLE7() extracts specific rows from the evaluation catalog
%   (evaluation_dataset_v2.csv) based on a predefined list of target
%   filenames or substrings. The output is saved as a CSV file for
%   Table 6 in the manuscript, illustrating representative batch vetting
%   cases.
%
%   METHODOLOGY
%   -----------
%   1. The function reads the unified evaluation catalog generated by the
%      master pipeline.
%   2. A cell array of target substrings (e.g., filenames or target IDs)
%      is used to filter the dataset.
%   3. For each target, the first matching row is selected; duplicate
%      occurrences (e.g., multiple quarters) are omitted to keep the
%      table concise.
%   4. The selected rows are displayed in the Command Window and exported
%      as a CSV file for use in the manuscript's Table 6.
%
%   USAGE
%   -----
%   generate_table7()                  % Uses default target list and output filename.
%   generate_table7(target_list)       % Uses a custom target list (cell array of strings).
%   generate_table7(target_list, outfile) % Custom target list and output filename.
%
%   DEFAULT TARGET LIST
%   -------------------
%   {'144440290','TOI_201.fits','278683844','quarter_10','Proxima', ...
%    '12557548.fits','11253226','V723_Mon.fits'}
%
%   INPUTS
%   ------
%   target_list : (Optional) Cell array of strings to search for in
%                 the 'Filename' column. Case-insensitive.
%   outfile     : (Optional) Name of the output CSV file. Default:
%                 'Table6_BatchVetting.csv'.
%
%   OUTPUTS
%   -------
%   CSV File : Table6_BatchVetting.csv containing selected rows.
%   Command Window Output : Summary table of the selected segments.
%
%   DEPENDENCIES
%   ------------
%   evaluation_dataset_v2.csv : Must be in the current directory.
%
%   SEE ALSO
%   --------
%   main_pipeline, readtable, writetable
function generate_table6(target_list, outfile)
    % Set default arguments
    if nargin < 1
        target_list = {'144440290','TOI_201.fits','278683844', ...
                       'quarter_10','Proxima','12557548.fits', ...
                       '11253226','V723_Mon.fits'};
    end
    if nargin < 2
        outfile = 'Table6_BatchVetting.csv';
    end

    % --- 1. Load the evaluation dataset ---
    csv_file = 'evaluation_dataset_v2.csv';
    if ~isfile(csv_file)
        error('File %s not found. Please ensure it exists in the current directory.', csv_file);
    end
    data = readtable(csv_file);
    data.Filename = string(data.Filename); % Ensure string type for compatibility

    % --- 2. Initialize output table ---
    table6_rows = table();

    % --- 3. Search for each target ---
    fprintf('\n=== Extracting Table 6 rows ===\n');
    for k = 1:length(target_list)
        kw = target_list{k};
        % Perform case-insensitive search
        mask = contains(lower(data.Filename), lower(kw));
        sub = data(mask, :);
        if height(sub) > 0
            % Take the first matching row (avoids duplicates for multi-quarter targets)
            table6_rows = [table6_rows; sub(1, :)];
            fprintf('  [%s] -> Matched: %s\n', kw, sub.Filename(1));
        else
            fprintf('  [%s] -> No match found\n', kw);
        end
    end

    % --- 4. Display and save results ---
    if height(table6_rows) == 0
        warning('No rows matched the target list. Output file will be empty.');
    else
        % Select columns of interest for display
        disp_columns = {'Filename','T_SNR','L_SNRAS','Suppression_pct','Tier'};
        disp(table6_rows(:, disp_columns));
        
        % Write to CSV
        writetable(table7_rows, outfile);
        fprintf('\n Table 6 saved to: %s\n', outfile);
    end
end
